[build]
  command   = "npm run build"
  publish   = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.environment]
SECRETS_SCAN_ENABLED = "false"
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL,STRIPE_API_VERSION"
SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**,STRIPE_SETUP.md"
